apiVersion: v1
kind: Service
metadata:
  name: docker-service
spec:
  selector:
    app: dockerpoc
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080


apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-deployment
spec:
  selector:
    matchLabels:
      app: dockerpoc
  replicas: 1
  template:
    metadata:
      labels:
        app: dockerpoc
    spec:
      containers:
        - name: dockerpoc
          image: dockerpoc:2.0
          ports:
            - containerPort: 8080